#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: 关于启蒙,关于工具,关于崇拜
#+DATE:<2020-04-16/Thursday 22:53:49>
#+KEYWORDS: 启蒙
#+LANGUAGE: zh-CN


* 关于启蒙
我能用linux,能用Emacs其实完全得益于早年的时候看了王垠在清华时期的博客.

当时他推荐的那些工具我特别喜欢.

有些甚至使用到了现在

现在我更加离不开这些
- linux, 让习惯了windows的我有了另外一种思维方式,让我看世界的方法和以前不一样改变了我很多的习惯.
- Emacs, 这个就不用说了,我的所有的生活都在emacs上面,都在org上.他完成我我所有想要的东西,然后还不用重复学习.
- Wget, 对于一个资料收集控来说Wget这个linux缺省安装的软件简直就是一个神奇,一个离不开的软件.
- Git, 还能说什么,作为一个资料收集狂魔,还有什么能比得上自己的文件服务器用Git来搭建呢.
- firefox, 我用firefox12年.我的知识体系,就在firefox的bookmarks中.
- IRC, IRC里面记录了我的青春,当年是在Emule上用的.
- bash, 一个命令一个脚本,一个管道,可以完成我及其任性的各种备份需要,不用重复学习.
  TAB, 自动补全,
- regex, 没有他我真的不知道怎么完成这些半自动化的工作


* 关于崇拜
wang在自己最新的博客内,很痛斥崇拜,

但是我有点无法接受这种思想,(或许我只是太普通)

因为,我选择这些工具,并不是因为我的信仰,我崇拜那些发明者.

因为他们设计了某些可以让普通人更好生活的工具,

他们谱写了我这样的普通人只能打拍子的乐曲,

崇拜没什么不好,也不可能因为崇拜而让猪油糊了双眼,

我开不出300迈的车速,但我可以为f1冠军摇旗呐喊,

我设计不出那些行之有效的软件,我可以为那些设计者奉上我的感激之情,更可以在能力范围之内改良到手的工具.

我喜欢这些家伙的思维方式,想要成为他们那样的设计者,那样从0-1的人.


* 工具就应该是古老的木柄手锤
我是有一些工具情节的人,

我不是程序员,但是我喜欢这些计算机工具,就像武士精心擦拭自己的武士刀一样,

我也会精心的维护这这些让我快乐的计算机工具.

因为我有需求,他们能帮我解决需求,而且刚好我会使用而已.

我也不必为了某个需求再去重新寻找和学习那些让我各种设置的炫酷软件,甚至逼着自己常识超出自己能力范围的事情.

这些工具可以让我,一次配置，任意更换环境,然后继续稳定工作,就像什么都没有更新一样.

这些工具就像一把老式木柄手锤,或者一把普通螺丝刀，我不要他的炫酷,我只要他稳定,可靠,随手可得,并且解决问题.

虽然,那些古老的工具,伴随着很多的不完美,和上古缺陷.

但是他依然最有效解决我的实际的问题,而不必付出过多的学习成本.

这就是我对工具的需求


* 关于完美性
任何的事务都不可能是完美的,

从事工科的我来说,我可以找到无数种可以解决单个问题的工具,

甚至我可以在我精通的领域发明一种比现有的工具更有效的解决工具,

(每个人都会有精通的领域,并不局限于计算机领域,我认为更重要的是一种思维的方式.而不是一些偷换概念的纯抬杠.)

但我通常不会,我的同事们也不会,因为我们不想,

更因为我们知道,根本就不存在完美,根本就不存在最优,

我们都选择适应,进而改良,

而创造,是最危险的.

任何工具存在的目的,只是为了解决问题,解决需求,

就像无法解决左撇子的写字顺序问题一样,

而正是不完美的存在才会留给思考更多的空间,

而改良和进步正是在这一刻发生的.

当然这个世界很需要这样的能解决问题的工具,越多越好,

但是同样这个世界更需要的是追求完美的心,

这也是很多艺术家,哲学家,数学家,地位如此之高的原因,

但讽刺的是数学家,哲学家,和艺术家却创造了最多的无法解释的不完美.

而我的成长正是站着这些带点瑕疵的巨人的肩膀上的.

我知道他们的不完美,我看得见脚下的瑕疵,

但是正是那些精华给了我刚刚看到沙滩的高度.


* 关于偶像
没人会在自己的成就超过曾经的偶像之后,

说出那些自己曾被偶像误导和早已经超过,那种不屑的言论.

这种言论,

非常像一个正在使用核能供电的现代人,怒斥几千年前的洞穴人发明的火把有多落后,有多少发明时期就伴随的设计问题,火把照明和烹饪有多难操作一样,

无知可笑.



* 关于悖论
这些想法想要表达我的无知和对知识的渴望,

但这些自己的坚定的见解使自己陷入一种仿佛自己的理论无懈可击的悖论当中去.

我想坚定的证明自己的想法是对的,

我越想这样,越会陷入到一种类似自我封闭的自信,和盲目排外的自大当中去.

我这么无知有时如何知道自己无知的.

我知道自己不知道我知道我不知道自己知道.


* 总结
上面的一切仅仅是我瞎扯淡.


