#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: 人类还有多少希望--<<美丽新世界>>
#+KEYWORDS: <<美丽新世界>>
#+LANGUAGE: zh-CN


人类还有多少希望《美丽新世界》读后感

在两本著名的反乌托邦小说中，人们忧心忡忡的《1984》并没有如期而至，而赫胥黎预言的《美丽新世界》却在日渐成为现实
——尼尔.波兹曼《娱乐至死》

故事设定在公元2540年（书中的福特632年）的伦敦，描述了与当今社会不同的新世界的一系列科技，新世界的人类不再依靠不稳定的两性繁殖，而全部依靠机械化规模化，流水线话的试管培植、并且在人还胚胎时期就进行大规模的筛检，分别出优等中等以及仅适合体力劳动的劣等人，并且在各类胚胎成长发育时期，运用各种条件制约、催眠等，严格控制各类人的喜好，让他们成年之后用最快乐的心情，去执行自己一生已被命定的消费模式、社会等级和岗位。从而保证社会稳定，快速发展，其实这类似于蜜蜂和蚂蚁的社会，确实是一种很高效极少浪费的模式。

同时为了解决社会的生产力不断发展的问题，整个社会大肆刺激消费，刺激旅游，还提供药物以及注射年轻血液等各种手段来延缓人类的衰老，整个社会依靠定量分配，号称拥有基督教和酒精的全部好处，却没有二者坏处的只会上瘾和带来欢乐没有任何副作用的新型毒品索麻来解决烦恼，和复杂的思考问题。从小所有人便教育成一旦有情绪，不管是疲劳、无聊等等，就立刻服用蘇麻，或者说蘇麻上瘾，在美丽新世界也不算副作用，因为有益于社会。“文明社会”里也没有宗教，当然不会有宗教，消灭一切信仰，神，哲学思考，消灭人独立生活的空间(独处是新世界中的人所不齿的行为，也是最不稳定的行为)，大肆提倡滥来交消灭人类作为生物的最基本的欲望(在大部分女人都被迫绝育的情况下与人睡觉已经变得如同今天与人问好一样简单，所有的男人女人都理所应当的认为自身都是共有的。)，那些家庭，父母，亲情，爱情，已经成为耻辱的代名词，问某人的父母是谁是新世界当中最恶毒的诅咒。所有需要的幸福条件已经都让人满足了(这些手段比起依靠监视和高压政策的1984不知道高到哪里去了)，至此美丽的，幸福的，永葆青春的，无烦恼的新世界构建完成。人类已经完全的人性泯灭，成为在严密科学控制下，身份被注定、一生虽然幸福无比，但却是如同蚂蚁和奴隶一般的生物。

全文其实可以分为两部分，第一部分是主角唐纳德在文明社会的生活，以及新世界背景的介绍，第二部分是野蛮人约翰来到文明世界的所见所闻，主线是围绕在唐纳德这样一个不起眼不出众的角色展开，这是一个说不上好，也称不上坏的一个人，并且整本书中我也没找到颜色鲜明的反面角色，一个个的人物中立而且鲜活，唐纳德在伦敦人类孵化以及控制中心上班，虽然是最高等级，却因为自己还是胚胎的时候，育种中心操作人员的失误而使身高不如第二等级，他在自己的等级备受歧视，并且感到孤单，也就是因为孤单导致的不幸福感，产生了对当时社会的思考。但是自身性格却又懦弱不堪，面对幸福来临之季，却又感觉喜欢上了这个社会。

有一次唐纳德他成功的约到了他的一位同事，孵化以及控制中心职员兰妮娜去今美国新墨西哥州“野蛮人保留区”的马尔白斯（Malpais）部落旅游，遇到了许多年前曾和育种中心主任汤玛斯前往该部落但因故未归居此的琳达，以及他俩的儿子约翰。而野蛮人约翰因为母亲琳达和部落的文化冲突等原因，受到其他印地安人排挤，且听闻其母所讲保护区外的故事，对“文明外界”向往。而柏纳德也用计和他合作，将琳达母子送到保留区外，到达那时代最大政权“世界国”重要城市伦敦，并且还利用野蛮人约翰成功的让其父亲主任汤玛斯辞职。

野蛮人约翰到伦敦后，当地人非常惊讶，因为野蛮人有太多使他们不解的地方。而野蛮人对社会多处也相当的难以了解。在母亲死后，他为了人生自由、解放城市人而努力，产生冲突，后来和柏纳德、其文学家好友赫尔默斯被押到世界控制者穆斯塔法‧蒙德前，四人也对社会的文化有所讨论。事后柏纳德和赫尔默斯称要被流放到外岛，而约翰也不愿被实验，离开伦敦，到一处废灯塔隐居，过着苦行的生活。但城市人仍蜂拥而来，白眼、取笑，最后的约翰绝望自尽。

1. 本书开篇的第一句，”一栋低矮的灰色建筑，只有三十四层，大门上写着中央伦敦孵化及控制中心，盾牌图案上刻着世界国的格言，社会，身份，稳定。”看完这句话，想到了这些熟悉而又威严的标语，到处张贴在个十字路口，公交车站，公共空间中，好的反乌托邦的书籍总能准确的预言到什么，而让那些被预言时代生活的人所震惊。有时候是触目惊心。

2. 关于等级，通过胚胎阶段的等级控制，牢牢的控制住了社会安定的第一根防线(简称第一岛链)，就像书中说的，统一生产的标准男女是社会稳定的主要工具。96个完全一样的多多生子，操作者96台完全一样的机器，上百万的多生子将解决一切问题，大量生产的原则终于适用于生物学了。是中的这点描述虽然与今天的现实相距甚远，但等级制度，等级观念，身份的固定化，从来不只是存在于几十年前的历史中，我们总被夸大其词的文学作品，艺术作品所感染，却总是忘记那同样血淋淋的现实。或许身在其中早已麻痹了吧，就像生活在新世界的人们一样。

3. 关于条件设定，睡眠疗法，古典制约，催眠，书中的作者，翻译者用了有这么多的名词来解释这些，现如今我们有更为贴切的，有丰富临床经验的特殊疗法，简称电击洗脑。智力发育尚未完全的婴儿，即在条件设定室中，被设定各种会跟随一生的条件反射，书中介绍了低等级的婴儿一接触到鲜花和书本就会被电击的设定过程，主管甚至得意洋洋的介绍，”看看吧，看看吧，假以时日他们会带着心理学家称之为条件反射的对鲜花和书本的厌恶长大，反应的条件就这样无可逆转的形成了，他们一辈子都不会在对鲜花和书本感兴趣。”，如果把书中的婴儿配上红领巾的话将是多么完美，遗憾的是，直到七八岁才能步入学校进行这些条件设定教育，多么的低效率，虽然群魔共舞的三尺讲坛弥补了不少真实世界的丢分项，但还是不能和书中相提并论。当然我们还有杀手锏，以用电大户杨叔为代表的一群人。

4. 关于思想，在胚胎阶段就划分好等级的人，自从在新世界诞生的那天起，包括在尚未成熟的婴儿期的时候，睡觉期间都会在枕头下面播放各种洗脑教育语录。让自己感觉自己的等级最幸福，别的等级最肮脏。让等级以及对自身等级的幸福感深入骨髓。针对个人的洗脑很可怕，但是更触目惊心的是针对群体甚至国家的洗脑。在那些尚未远去的疯狂时期，在那战火纷飞之前的年代，一出出比文学作品中更疯狂的事件轮番上演。在历史这个舞台上一个比一个更残忍更可怖更无底线的人类恶魔轮番主场，谎言是他们的武器，就像曾有一群人只知道世界上百分之九十的人生活在水深火热之中，他们的目标是去拯救这些人，可后来他们才明白原来这百分之九十就包括自己。荒唐可笑，又如此高明高效。

5. 关于社会稳定，稳定就要服从，服从就要先消灭不一致性，消除个体性。而个体性的彰显的基础在于个人的独特性，具体来说就是情绪、情感和思考。为了消除情感和情绪，除了先透过人工繁殖大量制造克隆人以瓦解家庭，及其连带的亲情，抑制任何两人之间的情感。然后再强制所有人不得独处，不是在工作就得娱乐，而且必须是团体工作团体娱乐，一方面以让所有人保持愉快，另一方面也让人没有时间思考。进而抵制不一致的人，抵制思考的人，最后，让这个世界没有任何艺术、科学、历史，让人不太能轻易的触发思考。从而制造一个只有我们没有我的稳定的美丽新世界。让人想起一句话，书籍是人类进步的阶梯，尤其是烧掉的那些。

6. 关于野蛮人，我感觉野蛮人是本书唯一的亮点，野蛮人的世界观与现如今的人类很相似，读这本书的时候有对野蛮人很强的代入感。我们感觉野蛮人很正常，但是全书中的角色，只有作家和总统能够理解他，他保留着新世界的人所不齿的所有品德，但在我看来，他保留着的是人类最后的希望，保留有爱，亲情，对美好的追求，还有人最最不能丢的对异性的美好欲望。其实，一边年前的人类来到现在也会被视为野蛮人，也会遇到各种各样的不适应，我们去到一百年后，也同样会被认为是野蛮人，也会被那是的文明给伤害。

7. 一口气读完之后合上书本闭上眼沐浴着阳光这种感觉就是快乐就是自由，此刻的我就是幸福的。可是广义的幸福究竟是什么，看到野蛮人仍保有人性深处最美好的向往的时候我确实感到很欣慰，但最终野蛮人约翰还是由于无法忍受而自尽，不禁在想人类还有多少希望，在这个连人都越来越趋向于流水线似的社会，也曾单纯的想，如今已经越来越文明，生活越来越便利，甚至娱乐，乃至艺术都到了一个爆发式生长的时代，为什么迷茫，失望却越来越甚至看到无数的沉醉于这些批量娱乐话的社会中不能自拔。不我们还有光明，就像有人说的虽然黑暗才是永恒，光明只是短暂的一瞬，但只要一点光明就能驱散永恒的黑夜，衡量一个事情，不是以自己的“利”“弊”为基础，而是以生命的真和美为尊则！可是，作为几十年之后的人来深深的思考一下，作者阐述的世界，对已某个人类个体而言，确实现在看起来是不幸的，但同时，可以想象，那样的文明，那样的科技，对整体的人类这个族群来说，却又是如此的效，如此的正确，不可改变，不能避免的，人类社会终究会朝着这个方向发展的。不禁感叹，书本中，真正的智者是那个总统，他看透了一切，但是最终还是服务于这个社会。哎，刚刚燃气的希望又被浇灭了。。。。

偶然想起机器人总动员这个动画片有着惊人的反乌托邦内涵，其中的太空船内社会结构与美丽新世界介绍的社会有着惊人的类似，并且与现实社会也更加的接近，我很喜欢那个小机器人瓦力，可是我更感兴趣的是，究竟在太空船中无所担忧的健康生活一辈子但是没有自由是对的，还是回到那个充满着垃圾但是有不可预知的未来的自由家园是正确的呢，我根本不可能知道答案，但我还是挺喜欢机器人总动员的结局的。

闭着眼睛沉思理想的社会什么样，拷问自己如果自己生活在那样的世界会怎样，最终我也没有找到答案，但是结合历史现实，我却明白了一个道理，那就是如果有人告诉你”理想的人类社会是什么样的。”，那就让他滚蛋。


1.一个民族只关心脚下的事情，那是没有未来的；一个民族有一些关注星空的人，他们才有希望；一个民族能审视灵魂，他们才有未来.——黑格尔 
