#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: 我的朝花夕拾
#+DATE:<2020-04-20-111/Monday>
#+KEYWORDS: collect
#+LANGUAGE: zh-CN

* [/////////                     ] 30%
今年过去了这些了
庚子鼠年着实不好过阿.


* 未曾清贫难成人,
不经打击老天真。
自古英雄出炼狱,
从来富贵入凡尘。
<2020-04-20/Monday 20:37:13>


* 铁指寸进，零秒精通
铁指寸进，零秒精通
<2020-04-13/Monday 20:06:15>


* 网路的事实 
在网络上, 每个事实都有一个大小相等, 方向相反的观点存在.
<2020-04-13/Monday 18:19:04>


* 你我皆凡人
很多时候我们都以为自己做好了完全准备
能承受失败,能承受失去
但我们中的大多数人终究只是一介凡人
稍微突破一些凡人认知的坏事降临,就足矣让我们感到恐慌.


* 发达国家
如何分辨国家是否发达？
来一场倾盆大雨，足足下它3个小时。
如果你撑着伞溜达了一阵，发觉裤脚虽湿却不肮脏，交通虽慢却不堵塞，街道虽滑却不积水，这大概就是个先进国家
如果发现积水盈足，店家茶壶头梳漂到街心来，小孩在十字路口用锅子捞鱼，这是个发展中国家。   
-- 龙应台


* 糖果
我们所做的一切都怀着美好的愿望。但年复一年，事与愿违


* 撒谎
他们在说谎
他们也知道他们在说谎
他们知道我们知道他们在说谎
我们也知道他们知道我们知道他们在说谎
但是他们依然在说谎
—索尔仁尼琴


* 思想是火把
人脑不是一个可以灌输知识的容器,而是一个可以点燃的火把
-----古希腊 生物学家散文家,,普多塔戈


* 扯淡精神
这个这个民族，扯蛋精神有的是什么头发丝上雕刻一首唐诗，大米粒雕刻一条小船，一个上千年前的尿罐子拍卖几千万元。2吨重的一块月饼，20个厨师做的一千斤的一锅蛋炒饭。这些记录对国家富强民族振兴有啥用处？发明车轮上千年，却发明不了轴承和轮胎。茅坑蹲了上千年，也没想去发明个马桶。丢人不？民族，扯蛋精神有的是，什么头发丝上雕刻一首唐诗，大米粒雕刻一条小船，一个上千年前的尿罐子拍卖几千万元。2吨重的一块月饼，20个厨师做的一千斤的一锅蛋炒饭。这些记录对国家富强民族振兴有啥用处？发明车轮上千年，却发明不了轴承和轮胎。茅坑蹲了上千年，也没想去发明个马桶。丢人不？



* 杜琪峰的告诫
“我年轻的时候，也想过连任，但是叔父辈跟我说，要退就退得漂漂亮亮，老了，还有人尊重。做见不得人的事，死路一条。”
——《黑社会·以和为贵》


* 历史上稀烂的车辙总是重复的一遍一遍的覆盖
变态嗜杀的义和团，血腥残忍的红卫兵，怒砸日本车或者家乐福的爱国贼，崇尚极权暴力的毛粉，护卫奥运火炬的红海洋，翻墙爱国变态嗜杀的义和团，血腥残忍的红卫兵，怒砸日本车或者家乐福的爱国贼，崇尚极权暴力的毛粉，护卫奥运火炬的红海洋，翻墙爱国的愤青小粉红，郭字号网络水军……令人震惊的不仅仅是他们一脉相承的群体性野蛮和下流，还有他们的愚蠢和癫狂。的愤青小粉红，郭字号网络水军……令人震惊的不仅仅是他们一脉相承的群体性野蛮和下流，还有他们的愚蠢和癫狂。



* 精神病
井冈山精神、长征精神、延安精神、雷锋精神、愚公精神、大庆精神、抗洪精神、抗震精精神病】井冈山精神、长征精神、延安精神、雷锋精神、愚公精神、大庆精神、抗洪精神、抗震精神、航天精神、张思德精神、白求恩精神、民族团结精神、艰苦奋斗精神、爱国主义精神、国际主义精神……等等精神。其实这个国家迫切需要的是另一种精神——契约精神，这是法制社会的基础。神、航天精神、张思德精神、白求恩精神、民族团结精神、艰苦奋斗精神、爱国主义精神、国际主义精神……等等精神。其实这个国家迫切需要的是另一种精神——契约精神，这是法制社会的基础。


* 当时罗马尼亚民众的大规模和平示威
当时罗马尼亚民众的大规模和平示威，遭到齐奥塞斯库所派内卫部队的血腥围剿屠杀，眼看就要成为“六四”第二，危急关头，是抗命的罗国国防军将领，愤而率军起义，并打开军火库向民众分发枪弹，奋起围歼内卫部队，方才扭转了失败的局势。
——《“苏东波”模式既非中国样板，也非“和理非”》


* 拒绝参与政治的惩罚---柏拉图
柏拉图有柏拉图有句名言：拒绝参与政治的惩罚之一，就是被糟糕的人统治。这是智者之语。可惜很多人不理解，甚至连听过都没有。中国历史总是不断的轮回，有时候真的不得不怀疑，这就是报应。所谓政治，本质上就是关于人和人关系的。所以，作为天生社会之人，本就是政治的。放弃政治，意味着放弃自己的社会权利。


* 爱国是爱什么
爱国不是爱政府，爱国不是爱某党。国家、政府和政党是不同的！有的时候政府和政党做的事恰恰是在卖国和误国。当你发现政府和政党在卖国和误国的时候，推翻这个政府、消灭这个政党即是爱国！


* 知识分子的理智
王小波：知识分子最怕活在不理智的年代。所谓不理智的年代，就是伽里略低头认罪承认地球不转的年代，也是拉瓦锡上断头台的年代，是茨威格服毒自杀的年代，也是老舍跳进太平湖的年代。我认为知识分子的长处只是会以理服人，假如不讲理，他就没有长处，只有短处，活着没意思，不如死掉。


* 流行的猖狂“汉奸”言论
A.香港人骂李鸿章，你多签几年租期会死啊？B.深圳人也骂李鸿章，你把地方签大一点会死啊？C.全国人民骂慈禧：你把全国签出去会死啊？D.又骂八国联军：都打下北京了，把政权拿过去会死啊？E.一网友说：再签一次会死啊？


* 这个时代从来没有改变
我读小学的时候，电子游戏被喉舌称为"电子海洛因"，游戏杂志因为质疑这个说法被停刊处理，中国禁止了所有游戏机和软件的进口，十几年后才放开。王者荣耀现在的遭遇，就是崔健说的：不要以为我比你们大十几二十岁，我们就不是一代人，只要天安门还挂着毛主席像，我们就都是一代人。
—郑褚Paul


* 社会赖以存在的基础
有没有感到失望，太失望了，对这样的人，这种问题的原因，是这个社会赖以存在的基础有问题，大家的价值观被扭曲，一切都是权钱名利，除此之外谁又去想那些心底真正对美好善良的向往。这些人什么都不懂，什么都不想去了解，也没有一个自己为之奋斗的目标，他们把自己的失败归结于别人的成功，如今这个社会犹如四十多年前差不多，网络就是他们新闻哥的阵地。


* 土地的归属权问题
说实话有时候在想，到底一片土地的归属，是谁说了算，是历史，是武力，是自古以来，是两个几千公里之外的国家，还是世代居住在这片土地的人民所谓的归属感，我搞不懂什么叫分裂，那些那片土地居住了一百多年的家族，那些真正把那片土地当做家园的人们，却被告知这不是你的土地你无法选择自己想要的生活方式，你没有管理权。在那些几个强权的一次交易中，各个大国的利益取舍里，受苦的终究是那些爱着这片土地的人，从没人问过他们想要什么。人类社会啊，悲哀。


* 他们害怕... ...
在布拉格听过一首当年的地下摇滚，歌词有意思:他们害怕老人的记忆，害怕年轻人的思想，他们害怕墓地的鲜花，害怕工人害怕教堂，害怕电影害怕画家和音乐家，害怕所有的快乐时光，害怕雕塑，害怕电台，害怕技术，害怕信息自由流动，害怕所有的波长。那么，我们为啥要害怕他们？


* 一个国家需要什么
一个正常的国家，不需要奸臣，也不需要忠臣，不需要昏君，也不需要明君。没有人是我们的君，我们不是任何人的臣民，没有人应该被统治！我们是平等的公民。我们雇你管理国家，不是雇你骑在我们头上拉屎撒尿，分清楚，你是我们雇的，干的好，还雇你干，干不好，滚蛋，换人，君君臣臣思想该结束了！


* 施恩者莫求回报，受恩者莫失良心
你让他感恩戴德，保不齐什么时候他就会捅你一刀，因为你的一次恩德，让他一辈子抬不起头来，总觉得亏欠，所以，施恩者莫求回报，受恩者莫失良心


* 讨厌的人
我们慢慢变成我们所讨厌的人，或许我们本身就跟讨厌自己


* 我们见过太少世面
匆匆那年 我们见过太少世面 只爱看同一张脸 那么莫名其妙 那么讨人欢喜 闹起来又太讨厌


* 意义
我所做的一切在你看来是垃圾，而在我眼中是我生活全部意义所在。


* 喝醉了
一个人喝醉了最想打电话给他的那个人，可能是你心底爱的最深最重要的人，因为人都是有防备心的，在最脆弱最没有防备心的时候最想的那个人肯定是内心最喜欢最信得过的。有句话是:如果，一个人醉酒之后，打电话给你，或者发信息给你，因为他在心里最深处的一个干净的角落里有你，或许他是爱你的，你是他的知心爱人；或许他是最需要你的，你是他的红颜知己；或许他是最需要你理解的，你是他的暧昧情人。

可无论你们是哪一种关系，不要打断他的话，他的话虽然语无伦次，毫无头绪，甚至连他自己都不知道自己说的是什么，你都应该庆幸，在醉酒后他想到的第一个人是你，他的内心深处那么的在乎你。人在醉酒后往往会把自己最真实的一面表露出来毫不伪装，而此时想到的第一个却是你，说明你在我心中是很重要的。

给自己一份勇气，打个电话给心里那个不可能的人。



* 远方和故乡
去不了的叫远方，回不去的脚叫故乡，忘不了的是初恋，舍不掉的是叫相好。


* 独处的时光,
那些你独处的时光，塑造了现在难相处的你。什么人这么难相处 因为这些人个性太强，独立观念太深，大多在童年经历过熬过一段孤独无助的时光，就像很久以前看到的那篇文章一样，或许太古怪，或许太自闭，或许太不合群，太不喜欢交流，其实他们用自己的毅力坚持过那些时光


* 权利和个性
想了解一个人的个性，那就赋予他权力。--林肯


* 专制制度下只有两种人
一种是哑子，一种是骗子。我看今天的中国就是少数骗子在统治多数哑子。--王亚南


* 关于抵制
不解为什么有那么多的抵制这货抵制那货的人存在，那些叫嚣抵制这货抵制那货的人，根本没有明白，在这个全球化的时代，是吗无有办法完全的地址某国的。谁也不知道手中的那个产品的生产工具，原材料，顶级供应商，是哪个国家的，技术传承在哪个国家，确实合资企业是为了国外的股东牟利的，但是也绝对不能忽略，这个拥有全世界最大人口数量的国家的劳动力解决问题是需要全世界的市场和公司一起努力才能解决的。那些为了股东牟利的合资企业甚至纯外资企业，为中国解决了多少的劳动力问题，在哪里赚钱的是自己的同胞，他们在华设立的企业，大部分的是绝对的为国家交税的。说不定国家的暴力机器里面就有在华日资企业上税所交的钱购买的弹药。这个问题有没有考路过，空谈爱国，与当时的颐和园又有什么区别，历史上就存在过闭关锁国的时代，历史书面镜子的话。他告诉饿哦们现在唯一的一点，就是落后就要挨打，自闭就会落后，试问有多少的民族企业的崛起是依靠从外资企业打工管理的国人经营们创立起来的呢。别的你们我们还不知道，科技方面，手机行业的黄埔军校摩托罗拉，汽车方面的大众，摩托车的honda，suzuki，yamaha，没有这些外资企业的注入资金，建设工厂，招收管理，传授技术，如何能够有今天的工业大国的地位，愤青们盲目的抵制日货，试问可曾知道在日本车厂中工作的是自己的同胞，全国都不买日本汽车，这部分的劳动力下岗的问题如何解决，在华日系车厂全面撤走，原材料的过生问题，如何解决，其实现在已经有这方面的担忧了，由于国内劳动力，已经消费水平的升高，很火跨国公司，已经开始寻找更便宜的劳动力市场了。

所有人其实就是一个整体，别人的不幸就是你的不幸，不要去问丧钟为谁而鸣，丧钟为你而鸣！


* 过去过不去
如果过去的就让它过去，以后只会更遭


* 灵感
梵高看见夜空，绘出了星轨的迁移。毕加索看见白鸽，他用来呼唤和平。安迪沃霍尔看见商品，深谙它复制品的本质。他们看见灵感，他们成了艺术。你看见了灵感，又将去往哪里？


* 吉田拓郎
每个人的成长过程中都或许有一段对于爱情迷茫的时期。

而我的迷茫时期，正是听着吉田拓郎的歌度过的


* 武士刀

人类冷兵器的巅峰之作 日本武士刀

一个把武器赋予了生命和信仰的民族所传承信仰和打造的.


* 社会教给我最重要的一句话

实力不如人，实力就是话语权，实力比人强，话语权就是实力。


实力相当，外交就是实力，实力悬殊，实力就是外交。

