#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: 我不原谅，曾经群魔共舞的三尺讲坛
#+KEYWORDS: 我不原谅
#+LANGUAGE: zh-CN



我不原谅，曾经群魔共舞的三尺讲坛

韩愈的《师说》 “古之学者必有师,师者,所以传道受业解惑也。”

今天读了一篇微信公众号朋友发表的关于一位教师和他的任性学生的智商以及情感交流。

读完之后我在想，想什么呢，想起自己的事情来了，我虽然没做过老师，但我做过学生，也算是稍有资格议论一下关于那时候我遇到的教育的问题吧，最反感那种特有的中国式流氓，你行你上不行别逼逼。还有就是感叹他的这位学生没有生活在我的那个时代，和庆幸遇到了他这么一位好的教师。
当时我马上给作者的回复就是，如果她生活在我的那个时代，那么她会面临着身心受巨大伤害的结局，也就是碰到了你，有时候想想这也算是教育的进步。

所以也就顺道想起了自己所处的那个三尺讲坛，群魔共舞的时代，作为一个90后第一代人其实这段回忆过去了也没有多久，这也是记忆犹新的原因吧。
那时候的我就像这位敢于直接漠视教师的学生一样，甚至在任性方面有过之而无不及，虽然我的任性使我走入了另一条更加艰辛的人生道路，但现在我不后悔我以前的任性，也许是因为是那一场场意外的任性，塑造了现如今的我，也正是那一拨又一拨的和权威和制度的较劲和任性，成就了我那我无论何时都任性一般只痴迷于自己感兴趣的知识的原因。所以没有后悔，唯一惋惜的是我那时候即使是对数学背后的逻辑稍有兴趣，却也没能搞定数学。
古人解释：师者传道授业解惑也，这也是如今大部分的教师以此来自居的信条，可是为什么我至今不解，用来传道授业解惑的知识是在何时被单纯的绑架成为前途的工具，是因为人口就业压力？还是那望子成龙的父母？还是就算进入了21世纪，仍然虔诚的信仰著书只为稻粱谋的封建毒瘤作祟，那历经十数年的教育更是沦为以后找工作就业的前期手段，无数的名校毕业生更是纠结于国企还是外企，这样的局面是知识存在的唯一理由吗，还有一点对这些历经数代人总结积累的经验，知识，的敬畏吗？我不知道，或许我的选择不对，这样的选择给我的成长造成了很多的艰难困苦，可我始终笃信，兴趣是知识发掘的唯一道路。

我经历过的那三尺讲坛在我的印象中简直就是群魔共舞一般的场景，四十分钟，你方唱罢我登场，照本宣科者，威逼利诱者，甚至嘲笑辱骂者，层出不穷，我不懂为什么师徒坐而论道的时代一去不返，什么事情都围绕着为师着者建立的绝对权威，动辄家长体罚伺候，为徒者就似惊弓之鸟一般为了成绩，为了夸奖，为了认可，为了自己将来的工作岗位，按部就班接受那定额定时定量的营养物质的推送，就像那高科技大棚里面无土栽培的西红柿一样，或者说更像为了提供顶级鹅肝食材而用管子“填养”的鹅。更有甚者带着那宣泄式的不怀善意的拳打脚踢，每每遇到这样的情景幼小的我可耻的因为惧怕而不敢言语，现在想来我岂不是从小就和解了一场又一场的刑事案件。
师与徒的信任更无从谈起，我不相信那时候的老师相信那些频繁的捡到过巨额资金的小学生，我从小学时代开始的语文作文题，就算是写实类的题材也从没要求务必真实过，所以，我上的第一堂完美的撒谎课就是一年级的语文作文。我时至今日仍不能原谅的是，我曾遇到过一位老师，要求我回家记录看到的动画片，我告诉他我从小学开始从不看动画片了已经，那句话讲完之后，从他的眼神中所折射出的，从他的背后所挥发出的那种深深的不信任感，让我至今想起来仍能清楚的记起他那干枯毛躁的卷发，和深深的惧怕，颤栗。

那个时候极难挑出一个同学，他能坦诚的告诉大家学习是为了兴趣，知识是为了爱好，我能每天捧起书本是为了安抚我那吱吱作响的好奇心，我更搞不明白的是为什么一个学生讨厌学习，从来没人问他原因，所有的爱他的人都只告诉他，你学习是为了你自己，为了你的前途，为了我们为人父母的面子，为了你那如火烛般燃烧青春为你奉献的家长老师。甚至我的老师拿出尖子生的理论来向我炫耀，你看人家这次考第二之后连续多少天不睡觉，就是为了下次考第一，你再看看你，整天搞这些乱七八糟的做什么，我真想硬生生的回复她，我搞得这些在你看来是垃圾，但在我看来这是我的毕生所爱，我为了愉悦自己，但他爱他那些背的滚瓜烂熟的诗词吗？他理解那些语言的优雅吗？她能感受那仿佛上帝总结出来的公式的美吗？你去问问他，他爱的是那个第一，是那个名次，如果以睡懒觉来排名谁是第一的话，他也能得。我不否认，国人的受教育水平在这样的条件下得到了极大的提升，但每次看到那临别学校之际，漫天飞舞的书本讲义碎屑，我都为那些被切割粉碎打成纸浆做成书本的小树悲哀。是什么让他们这么憎恨知识，是什么让他们如此仇恨。

反抗，作为学生一直都在刚反抗，一直在与权威斗智斗勇，无休止一般，轮回一般，从来没人问他们喜欢什么，肆意的凭自己的一厢情愿强行给那一页页的白纸任意涂抹色彩鲜明的美丽画卷，就像奥运会前闹得沸沸扬扬的马家军兴奋剂事件一般，体育运动原本是为了身体健康，可劳累一生的身体垮掉之际，能感受到痛楚的也之后那曾经打了兴奋剂的身体。
