#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: 夏日午夜的电子厂食堂
#+KEYWORDS: collect
#+LANGUAGE: zh-CN


这已经是多年前流行的名词了--血汗工厂，那时候的新闻上也连续曾报道某某知名代工厂员宿舍n连跳，甚至有些厂区宿舍夸张的在一楼外墙设置了防跳网，网络上面也是铺天盖地的针对厂方的负面评论，有指责，有怨恨，甚至谩骂.，这个词也一度成为年度热词。

偏偏就是在血汗工厂处在舆论的风头浪尖的时刻，我来到了常熟，来到了这样的工厂，并且浅浅的了解了一下这样的工厂。在东南沿岸的打工者口中这些工厂有一个统一的名字叫做“电子厂”，密集劳动力流水线生产式电子原材料或者成品组装厂，大部分是台企，或者合资。不出二里地能见到七八个世界五百强，不在哪个世界五百强工作，出门坐公交都不好意思跟人打招呼。

由于是自己只身一人去的那边，刚去的时候挺孤独的其实，后来慢慢也有了几个好朋友。一起上班一起下班，一起玩，相处时间长了，慢慢了解到，和我是同龄人的他们出来打工已经四五年之久了，当时的我惊叹于他们的阅历丰富，也同情他的成长环境，在我上高中迷茫于那些声色犬马的时候，他们就已经出来打工了好多年了，我沉迷于上课睡觉放学上网抽烟的年级的时候，他已经离开家乡父母奔波于远方了，甚至有几次过年都没归家，仅仅为了多赚一点加班费，那时候刚好网上铺天盖地的声讨电子到工厂超时加班的问题，甚至直到现在都有人在反对这个问题。网络上的那些伪公知也是一片伟光正的声音，其实真正了解的人都知道，如果赶上电子产品的淡季，基本是不会加班的，可是按当地的薪资标准一天不加那两个小时的班，那拿到手的工资就会少的可怜，我记忆中就有次连续几个星期没有班，大家的心情都很低落，有的甚至已经开始想着换厂了，找到那些订单仍旧很多的电子厂，去赚加班费 ，有人问这不是自己给自己找累吗？其实道理很简单，出来都是为了赚钱，不是为了安逸的。但舆论并不管当事人的实际需求，伪公知们更是站在自己的角度思考问题，跟风的大众更是看热闹不嫌事大的转发，而最后受到伤害的只有那些梦想着出来过获得丰厚报仇的当事人打工者，当时的我们虽然获得了双休，和那百无聊赖的每天两小时，但一个月下来损失的是几千块钱。毕竟不上班双休出去玩还是要花钱的嘛。舆论对于加班的问题的扩大，最难受的还是厂方，清闲的时候不给员工班家，员工怨声道载，纷纷离职，厂房压力很大，一忙起来订单压力大起来，舆论又不让给员工加班，产品做不出来，订单拖欠的压力越来越大，只能提高单位时间内员工的产能，提高了产能产品的良率就越低，良率越低，员工自己的心理压力就越大，这样久而久之的恶性循环造成了一出出的闹事，罢工，甚至造成了许多前面提到过的悲剧性事件。也有人提到过另外的解决方案，提高当地的最低基本工资解决这个问题了，当时确实盛行这样的言论，堂堂的天下苏杭，为嘛基本工资这么低，后来看的多了，才明白这个终极问题是多么的牢不可破，中国的人口数量决定了，中国以前现在以及未来的长时间以内，必须依靠劳动密集型企业来解决自身的人口压力问题，想要依靠这些企业这些工厂来解决劳动力和就业岗位的问题，就必须保持国家和城市的吸引力，如何保持吸引力，特别是面对现在新兴的世界工厂国家，像马来西亚，巴西，印度，泰国，等等。曾经的政策开放交通水电等基础设施的便利的优势已经被这些新兴的世界工厂国家一步一步的蚕食，剩下的只有从业者受过的教育程度这一点优势了，特别是薪资方面，面临着消费水平的提高已经有许多的跨国企业选择不在中国设厂了，如果单方面的提高了最低基本工资，面对的是整个城市将全面的失去竞争力，企业出逃，打工者就不来，打工者不来，已经为了外来人口建立起来的一整套的基础设施是这个城市的当地人自己消化不了的，整个城市的活力就会消失，甚至沦为鬼城。

就像伯林最著名的那篇《刺猬和狐狸》所说的，之所以有人本着一颗好心，说的做的是对的事，但却起到了反效果，就因为看问题的局限性，就像刺猬一样，只看到了这个一事件的问题，只想到一个解决方案。而忽略了全面性，最重要的一点就是忽略了他们想保护的弱势群体人们到底需要什么。忽略了一件事情的连锁反应和蝴蝶效应所带来的后果，不能因为自己有影响力有眼球效应，就按照自己的一厢情愿，不考虑他人的实际需要。

这些工厂最出名的是那个靠着给苹果代工而闻名的富士康。而我去的是和富士康同属台湾电子五哥的广达集团旗下苏州达富电子。不知道什么原因，我还真的很喜欢哪里的工作环境，仿佛大学城一般的员工宿舍，水电暖，洗澡间，电影院，阅览室，整洁干净宽敞明亮的餐厅，还有那夏天坐了拉肚子，冬天坐能粘在上面的石凳子，深夜村中的黑网吧，网吧旁边那个失火的小卖店，宿舍旁边撑到吐掉的葱油饼，当然还有那潮湿闷热让我羽绒服发霉的天气。这就是我每天的生活，像个二逼青年一样口袋里装满硬币，在那一天天的伴随着硬币哗啦声晃来晃去。自由散漫，天真快乐，

