#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: 手机
#+KEYWORDS: 手机
#+LANGUAGE: zh-CN


提起那些年的的手机，回忆起自己曾经对于一款新手机的激情，怀念满身独门秘籍，充满着对那个年代来说的黑科技，的工艺先驱和技术大鳄们，他们是一个时代的标志，他们更是我的青春。

那些和我年龄相仿的八零或者九零后年轻人，对属于父辈们的第一支手机，一般印象不外乎两个品牌，如雷贯耳的摩托罗拉，和大名鼎鼎的诺基亚，当然了可能还有爱立信，西门子，奥克斯，东芝，松下，当然国产的熊猫，科建，tcl 当然不能忽略了战斗机波导。但在那时一提起手机，最先想到的无外乎摩托罗拉和诺基亚这两个品牌。依稀记得曾经经典的顺口溜，我左手一个诺基亚右手一个摩托罗拉，移动联通小灵通，一天我换仨。

说实话我倒是挺喜欢那个科技半启蒙时代的，各个手机厂商为了博得用户的青睐，无所不用其极，与今天的手机同质化之严重形成鲜明对比。当然也可能是因为那时的信息获取渠道很单一的原因吧，那个年代每出一款手机之前总是热心的期盼，意淫着终有一天用上最新款，特别对手机外形尤其亲睐，那个年代的诺基亚换壳现象严重，摩托罗拉想靠一部v3来设计风格主导几乎所有生产线，但没办法，就是买账啊。就是喜欢，就是喜欢那个蛮荒的时代，设计师的灵感被无线扩大的年代，喜欢那些特立独行的产品。唯一烦恼的，也就是那没大有质感的塑料手机实体键盘掉漆之后的丑陋感挺让人讨厌的吧。

当时以及出现出现智能手机这个概念好久了，也很热烈的讨论智能和半智能的区别，反而现在极少见人们提起了智能手机这四个字了，确实，在现在这个电视机都智能的时代，老年机都安卓的时代，也只能讨论一下谁的手机不是智能的了。

不同于现在的系统三分天下(两分江山)，那是功能机刚刚开始向智能迈进的开端，那是真正的春秋战国，那是一个手机系统百家争鸣的时代，诺基亚当家的塞班，摩托罗拉的linux，微软的ppc，spc.三星和爱立信也都有塞班和pc系统，当年国内还叫多普达，有各种的ppc，spc，键盘触屏，各种古怪有如针头一般的外形，依然记得多普达更是高智商的代名词，有钱没文化就用诺基亚，脑子不好使别用多普达。诺基亚当家的塞班更是从s40玩到了s60.每用一个新版本都像是开辟一个新大陆一般激动。

永远忘不了的是那第个次拥有v3之前的一个晚上，辗转反侧侧夜难眠，如今没经历过那个时代的人，根本无法想象当03年razer v3横空出世的盛况，不做今天，真的有如布加迪出的这款做跑车带给我的感觉差不多，他是那么的科幻，那么的超前，零三年，穿着棉裤坐在炉子旁的我从电视上看到v3的那种深深的震撼，你能想象吗，刀锋，razer，当时根本没有胆量奢望自己将来能够拥有，和现在也同样不敢奢望自己将来能够拥有一部布加迪是一样的。

那时候拿着3m内存的v3，下载上几首500多kb的歌，还要和别人比拼音质，还记得那被60万像素摄像头的l7略的日子，现在虽然摄像头几千万像素了，可是拍照的那种清晰感，却再也体会不到了。即使是看到最新的iphone7的那块惊艳的屏幕，可心中早已波澜不惊了。

甚至自己使用多年的iphone连默认的铃声和壁纸都不换了.
