#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: emacs添加有道辞典教程
#+KEYWORDS: emacs添加有道辞典教程
#+LANGUAGE: zh-CN



* github网址
https://github.com/xuchunyang/youdao-dictionary.el


* youdao-dictionary.el
#+INCLUDE: "~/.emacs.d/lisp/youdao-dictionary.el" src emacs-lisp


* 依赖包和教程在作者github内..

;;; youdao-dictionary.el --- Youdao Dictionary interface for Emacs

;; Copyright © 2015-2017 Chunyang Xu

;; Author: Chunyang Xu <xuchunyang56@gmail.com>
;; URL: https://github.com/xuchunyang/youdao-dictionary.el
;; Package-Requires: ((popup "0.5.0") (pos-tip "0.4.6") (chinese-word-at-point "0.2") (names "0.5") (emacs "24"))
;; Version: 0.4
;; Created: 11 Jan 2015
;; Keywords: convenience, Chinese, dictionary

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
