#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: date-calendat-使用教程
#+KEYWORDS: linux-command, linux
#+LANGUAGE: zh-CN

* date命令
** date命令基本操作
+后面可以跟各种格式控制符来指定日期和时间的显示格式.例如,date +%Y-%m-%d会显示当前日期m格式为 "年 - 月 - 日",如 "2025-01-06".
常用的格式控制符包括：
#+CAPTION: date命令基本操作
| %a+%A    | 星期的简写+星期的全称 |
|----------+-----------------------|
| %b+%B    | 月份的简写+月份的全称 |
|----------+-----------------------|
| %D       | mm/dd/yy格式          |
|----------+-----------------------|
| %c       | 当前时区的时间        |
|----------+-----------------------|
| %e+%d+%m | 去零的日期+日期+月份  |
|----------+-----------------------|
| %H+%M+%S | 24小时制式的时间+秒数 |
|----------+-----------------------|
| %j       | 一年中的第几天        |
|----------+-----------------------|
| %n       | 换行现实              |
|----------+-----------------------|
| %Y+%y    | 全称的年和简写的年    |
|----------+-----------------------|
| %U       | 一年中的第几个星期    |
|----------+-----------------------|

** date --date :: 计算时间
date命令的 --date 参数
可以让date命令按照指定的时间来显示结果
但是我没有想到的是 --date 参数居然支持进行时间的加减运算

下面这段说明摘自 man date
#+BEGIN_EXAMPLE
DATE STRING
       The --date=STRING is a mostly free format human readable date string such as "Sun, 29 Feb 2004 16:21:42  -0800"
       or  "2004-02-29  16:21:42"  or even "next Thursday".  A date string may contain items indicating calendar date,
       time of day, time zone, day of week, relative time, relative date, and numbers.  An empty string indicates  the
       beginning  of  the  day.   The  date  string format is more complex than is easily documented here but is fully
       described in the info documentation.
#+END_EXAMPLE

换句话说，我们可以用它来进行日期间的加减运算,下面是一些例子:

    计算2018年11月22日再过60天是什么时候
    #+BEGIN_SRC shell
    date --date '2018-11-22 + 60 days' +'%Y-%m-%d'

    2019-01-21

    #+END_SRC
    计算2018年11月22日，前50天是什么时候
    #+BEGIN_SRC shell
    date --date '2018-11-22 - 50 days' +'%Y-%m-%d'

    2018-10-03
    
    #+END_SRC

    还可以加上时分秒
    #+BEGIN_SRC shell
    date --date '2018-11-22 01:02:03 HKT +12 days +12 hours +15 minutes'

    2018年 12月 04日 星期二 13:17:03 HKT

    #+END_SRC





* cal calender命令

** 配置文件
#+INCLUDE: "~/.emacs.d/loadfile/pengshao-calendar.el"

** 添加代办事项
在Calendar中可以为指定的日期添加代办事项:

- 使用i d命令为指定日期添加代办事项 
  在calendar中输入i d命令后,Emacs会打开一个教diary的文件,并自动填入光标所处的日期信息
  只需要接着输入代办事项的信息并保存就可以了

- 使用i w命令为每周的某一天添加代办事项
  可以使用i w命令建立每周例行任务

- 使用i m命令为每月的某一天添加代办事项
  我们可以使用i m命令建立每月例行任务

- 使用i y命令为每年的某一天添加代变事项 
  可以使用i y命令建立每年的例行任务

- 使用i a建立周年纪念日
  跟i y命令类似,但calendar会记录起始年份
- 使用i b命令为一个时间段添加代办事项
  将光标和mark放置在一段时间的起始/结尾处,按下i b键,Calendar自动插入时间段的信息我们只要输入待办事项的信息就行了

- 使用i c命令定义一个循环事项
  按下i c后,calendar提示输入循环间隔的日期
  虽有Calendar自动插入代表循环的时间信息,我们只需要输入代变事项的信息就行了

  命令 	说明
- i d 	添加待办事项
- i w 	添加每周例行任务
- i m 	添加每月例行任务
- i y 	添加每年例行任务
- i a 	添加周年纪念日
- i b 	为一段时间添加待办事项
- i c 	添加循环事项

** 日期信息

将光标定位到指定的日期处后,Emacs还提供了一些命令来获取光标所处日期的信息. 常用到的命令有:

- 使用p d命令显示光标所处日期是当年中的第几天

- 使用p C命令显示光标所处日期的农历信息

- M-=计算一段时间的天数
  在要计算时间段的起始天数/结束天数用命令C-@定义为mark
  然后将光标移动到时间段的结束天数/起始天数,这就定义了一个时间段区域
  按下M-=后就会在minibuffer中显示该时间段包含的天数
  该天数包含了起始天数和结束天数的.

- 使用h命令查看光标所处日期的假期信息
  如果光标所处的日期并没有假期,则Emacs在minibuffer提示No Holidays known
  否则则显示该日期对应节假日的名字.
  Emacs内置了一些常见的节假日信息
  另外,Emacs也提供了一些函数供我们自定义节假日:
  
  #+BEGIN_SRC lisp
  (holiday-fixed m d 节日名) ;定义m月的第d日为xx节假日
  (holiday-float m w n 节日名) ;定义m月的第w个星期的第n天为xx节假日,默认周日为第0日
  #+END_SRC


- 使用a命令查看所有三个月的假期信息 按下a键后,Emacs会在另一个窗口显示calendar中三个月期间内的所有节假日信息.

  使用x命令在calendar中标示出所有为节假日的日期来
  若我们想让calendar自动标示出节假日的日期来
  则更改calendar-mark-holidays-flag的值为非nil即可
  
  #+BEGIN_SRC lisp
  (setq calendar-mark-holidays-flag t)    ;让calendar自动标记出节假日的日期
  #+END_SRC


- 使用d命令显示光标当前日期的代办事项
  可以在d命令前加上一个数字n,表示显示n天内的所有代办事项

- 使用m命令在calendar中标记出所有记有待办事项的日期 
  该命令跟x类似,只是它标记出的是带有待办事项的日期. 
  你也可以通过更改变量calendar-mark-diary-entries-flag的值为非nil来让calendar自动标记出记有待办事项的日期.

  #+BEGIN_SRC lisp
  (setq calendar-mark-diary-entries-flag t)    ;让calendar自动标记出记有待办事项的日期
  #+END_SRC

- 值得一提的时,如果你将记录某项代办事项但却不想被标记出来,只需要在执行插入待办事项的命令前执行C-u就行了(就像C-u i d这样).
  
- 使用u命令去除calendar中的标记

命令 	说明
- p d 	显示当前日期是当年的第几天
- p C 	显示当前日期的农历信息
- M-= 	计算一段时间的天数
- h 	查看当前日期的假期信息
- a 	查看三个月内的所有节假日信息
- x 	标记出calendar中所有为节假日的日期
- d 	查看指定日期的待办事项
- m 	标记出calendar中所有记有待办事项的日期
- u 	清除calendar中的标记


** 导出为HTML
Emacs提供了两个命令来将日历信息,节假日信息和待办事项信息一起导出成HTML文件供我们查看,这两个命令为:
- 命令 	说明
- H m 	导出单月的日程安排信息
- H y 	导出当年的每个月的日程安排信息
  	 
** 约会提醒功能

1. 用M-x appt-activate开启约会提醒功能 要使用约会提醒功能,先需要开启appointment通知功能,命令是M-x appt-activate
2. 随后使用M-x appt-add命令来添加一个约会提醒. 执行app-add命令后,在Emacs提醒你依次输入约会开始的时间,提醒的消息,和提前多少分钟开始提醒. 虽有在离约会还有指定分钟的时候,Emacs会在底部弹出一个窗口,窗口的内容显示了指定的提醒消息.
3. 使用M-x appt-delete来删除一个约会提醒 执行appt-delete后,Emacs依次显示所有添加的约会提醒,并询问是否删除,按y表示删除,按n表示保留

- 在mode-line上显示约会提醒的倒计时 通过设置变量appt-display-mode-line的值为非nil,Emacs会在mode-line上显示还有多少分钟到下一个约会的倒计时.
  #+BEGIN_SRC lisp
  (setq appt-display-mode-line t)         ;在mode-line上显示还有多少分钟到约会的倒计时
  #+END_SRC
  
- M-x appt-activate 	开启appointment提醒功能
- M-x appt-add 	添加一个约会提醒
- M-x appt-delete 	删除约会提醒
