#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: ln-链接命令相关的教程
#+DATE:<2020-05-12-133/Tuesday>
#+KEYWORDS: linux-ln
#+LANGUAGE: zh-CN


* 硬链接和软链接
硬链接:ln source_file dist_file

软链接:ln -s source_file dist_file

软硬链接的区别：硬链接相当于一个文件两个名称,而软链接相当于创建指向源的快捷方式.


* ln命令选项
#+BEGIN_EXAMPLE
--backup[=CONTROL]  为每个已存在的目标文件创建备份文件
-b        类似--backup，但不接受任何参数
-d, -F, --directory   创建指向目录的硬链接(只适用于超级用户)
-f, --force     强行删除任何已存在的目标文件
-i, --interactive           覆盖既有文件之前先询问用户；
-L, --logical               取消引用作为符号链接的目标
-n, --no-dereference        把符号链接的目的目录视为一般文件；
-P, --physical              直接将硬链接到符号链接
-r, --relative              创建相对于链接位置的符号链接
-s, --symbolic              对源文件建立符号链接，而非硬链接；
-S, --suffix=SUFFIX         用"-b"参数备份目标文件后，备份文件的字尾会被加上一个备份字符串，预设的备份字符串是符号“~”，用户可通过“-S”参数来改变它；
-t, --target-directory=DIRECTORY  指定要在其中创建链接的DIRECTORY
-T, --no-target-directory   将“LINK_NAME”视为常规文件
-v, --verbose               打印每个链接文件的名称
--help    显示此帮助信息并退出
--version   显示版本信息并退出
#+END_EXAMPLE


* 硬链接
建立硬链接时,在另外的目录或本目录中增加目标文件的一个目录项,这样,一个文件就登记在多个目录中.

创建硬链接后，己经存在的文件的I节点号（Inode）会被多个目录文件项使用.

一个文件的硬链接数可以在目录的长列表格式的第二列中看到，无额外链接的文件的链接数为l.

在默认情况下,ln命令创建硬链接.ln命令会增加链接数,rm命令会减少链接数.一个文件除非链接数为0.

否则不会从文件系统中被物理地删除.

不能对目录文件做硬链接.不能在不同的文件系统之间做硬链接.链接文件和被链接文件必须位于同一个文件系统中.

** 需要查看硬链接的所有文件的位置
1. ls -il 查看文件的inode
2. find / -inum  inodenum


* 符号链接,软连接

与硬链接不同的是,符号链接确实是一个新文件当然它具有不同的I节点号,而硬链接并没有建立新文件。

符号链接没有硬链接的限制,可以对目录文件做符号链接,也可以在不同文件系统之间做符号链接.

用ln -s命令建立符号链接时,源文件最好用绝对路径名,这样可以在任何工作目录下进行符号链接.

而当源文件用相对路径时,如果当前的工作路径与要创建的符号链接文件所在路径不同,就不能进行链接.

在目录长列表中,符号链接作为一种特殊的文件类型显示出来,其第一个字母是l.
符号链接的大小是其链接文件的路径名中的字节数.

当用ln -s命令列出文件时，可以看到符号链接名后有一个箭头指向源文件或目录，例如
#+BEGIN_SRC shell
lrwxrwxrwx … 14 jun 20 10:20 /etc/motd->/original_file
#+END_SRC  
其中,表示“文件大小”的数字“14”恰好说明源文件名original_file由14个字符构成.
