#+SETUPFILE: ~/.emacs.d/org-other-file/org-level-1.org
#+TITLE: linux系统信息查询教程
#+DATE:<2020-04-22-113/Wednesday>
#+KEYWORDS: linux, systeminfo-linux
#+LANGUAGE: zh-CN


* neofetch
neofetch可以显示很酷的带图片的信息
多用于分享使用
#+BEGIN_EXAMPLE

       _,met$$$$$gg.        pengshao@ps-debian 
    ,g$$$$$$$$$$$$$$$P.     ------------------ 
  ,g$$P"     """Y$$.".      OS: Debian GNU/Linux 10 (buster) x86_64 
 ,$$P'              `$$$.   Host: VMware Virtual Platform None 
',$$P       ,ggs.     `$$b: Kernel: 4.19.0-8-amd64 
`d$$'     ,$P"'   .    $$$  Uptime: 15 mins 
 $$P      d$'     ,    $$P  Packages: 1847 (dpkg) 
 $$:      $$.   -    ,d$$'  Shell: bash 5.0.3 
 $$;      Y$b._   _,d$P'    Resolution: 1440x900 
 Y$$.    `.`"Y$$$$P"'       DE: Xfce 
 `$$b      "-.__            WM: Xfwm4 
  `Y$$                      WM Theme: Default 
   `Y$$.                    Theme: Xfce [GTK2], Adwaita [GTK3] 
     `$$b.                  Icons: Tango [GTK2], Adwaita [GTK3] 
       `Y$$b.               Terminal: emacs 
          `"Y$b._           CPU: AMD Ryzen 3 2200G (3) @ 3.749GHz 
              `"""          GPU: VMware SVGA II Adapter 
                            Memory: 1418MiB / 2024MiB 
                        

#+END_EXAMPLE


* GUI软件来查看系统的硬件信息---最简单
1.  i-nex 收集硬件信息，并且类似于 Windows 下流行的 CPU-Z 的显示。
2.  HardInfo 显示硬件具体信息，甚至包括一组八个的流行的性能基准程序，你可以用它们评估你的系统性能。
3.  KInfoCenter 和 Lshw 也能够显示硬件的详细信息，并且可以从许多软件仓库中获取。


* 查看系统信息
** uname -a 
输出系统信息
-a 查看所有
-r 查看内核
-p 处理器
-m 机器硬件信息
-i 硬件平台信息
** 查看系统内核版本
cat /proc/version
** cat /etc/issue
此命令适合所有linux发行版
** lsb_release -a
列出所有的版本信息
** evn
查看所有的环境变量
** hostname
查看计算机名


* CPU 详细信息

使用 lscpu 命令或与它相近的 lshw 命令查看 CPU 的详细信息：
#+BEGIN_SRC sh
$lscpu
$lshw -C cpu
#+END_SRC

使用这些命令的时候，你可以通过使用 grep 命令过滤复杂的信息，并缩小所需信息范围。

1. 只查看 CPU 品牌和型号:
   lshw -C cpu |grep-i product
   #+BEGIN_SRC shell
   $sudo lshw -C cpu | grep -i product
   product: AMD Ryzen 3 2200G with Radeon Vega Graphics
   #+END_SRC
   

2. 仅查看 CPU 的速度（兆赫兹）:
   #+BEGIN_SRC sh
   $lscpu|grep-i mhz
   #+END_SRC
   或其 BogoMips 额定功率:
   #+BEGIN_SRC sh
   $lscpu|grep-i bogo
   #+END_SRC
   
3. grep 命令的 -i 参数代表搜索结果忽略大小写。

** cpu和gpu的监控工具
1. sensor
2. Glances
3. i7z


* 硬盘使用情况
1. 显示每个磁盘设备的描述信息：
   #+BEGIN_SRC shell
   $lshw -short -C disk 
   #+END_SRC

2. 通过以下命令获取任何指定的 SATA 磁盘详细信息，例如其型号、序列号以及支持的模式和扇区数量
   #+BEGIN_SRC shell
   $hdparm -i /dev/sda
   #+END_SRC
   
   当然，如果需要的话你应该将 sda 替换成 sdb 或者其他设备号。

3. 要列出所有磁盘及其分区和大小，请使用以下命令：
   #+BEGIN_SRC shell
   $lsblk
   #+END_SRC
   
4. 使用以下命令获取更多有关扇区数量、大小、文件系统 ID 和 类型以及分区开始和结束扇区：
   #+BEGIN_SRC shell
   $fdisk-l
   #+END_SRC
   
5. 要启动 Linux，你需要确定 GRUB 引导程序的可挂载分区。你可以使用 blkid 命令找到此信息。它列出了每个分区的唯一标识符（UUID）及其文件系统类型（例如 ext3 或 ext4）：
   #+BEGIN_SRC shell
   $blkid
   #+END_SRC
   
6. 使用以下命令列出已挂载的文件系统和它们的挂载点，以及已用的空间和可用的空间（兆字节为单位）：
   #+BEGIN_SRC shell
   $df -m
   #+END_SRC
   
7. 最后，你可以列出所有的 USB 和 PCI 总线以及其他设备的详细信息：
   #+BEGIN_SRC sh
   $lsusb
   #或者 
   $lspci
   #+END_SRC
   
8. 查看文件夹的使用情况和大小
   #+BEGIN_SRC sh
   $du -sh <文件夹>
   #+END_SRC
   

* 内存相关查询教程

** 查看内存使用情况
#+BEGIN_SRC sh
$free -m -h
#+END_SRC
-h 用gb和mb现实便于阅读

** dmidecode命令来显示内存相关的知识

1. 使用 dmidecode 命令列出每根内存条和其容量：
   #+BEGIN_SRC sh
   $dmidecode -t memory | grep-i size
   #+END_SRC
   
2. 使用以下命令获取系统内存更多的信息，包括类型、容量、速度和电压：
   #+BEGIN_SRC sh
   $lshw -short -C memory
   #+END_SRC
   
3. 你肯定想知道的一件事是你的计算机可以安装的最大内存：
   #+BEGIN_SRC sh
   $dmidecode -t memory | grep-i max
   #+END_SRC
   
4. 现在检查一下计算机是否有空闲的插槽可以插入额外的内存条。你可以通过使用命令在不打开计算机机箱的情况下就做到：
   #+BEGIN_SRC sh
   $lshw -short -C memory | grep-i empty
   #+END_SRC
   输出为空则意味着所有的插槽都在使用中。


* 显存查看 
1. 使用 lspci 列出所有设备信息然后过滤出你想要的显卡设备信息:
   #+BEGIN_SRC sh
   $lspci | grep -i vga
   #+END_SRC
   
2. 视频控制器的设备号输出信息通常如下：
   #+BEGIN_SRC sh
   $00:02.0 VGA compatible controller:IntelCorporation82Q35ExpressIntegratedGraphicsController(rev 02)
   #+END_SRC
   
3. 现在再加上视频设备号重新运行 lspci 命令：
   #+BEGIN_SRC sh
   $lspci -v -s 00:02.0
   #+END_SRC
   
4. 输出信息中 prefetchable 那一行显示了系统中的显卡内存大小:
   #+BEGIN_SRC sh
   ...
   Memory at f0100000 (32-bit, non-prefetchable)[size=512K]
   I/O ports at 1230[size=8]
   Memory at e0000000 (32-bit, prefetchable)[size=256M]
   Memory at f0000000 (32-bit, non-prefetchable)[size=1M]
   ...
   #+END_SRC
   


* 进程相关命令

** ps -aux
#+BEGIN_SRC sh
$ps -aux 
$ps -ef
#+END_SRC
这是两张方式,经常使用第一种方式
后面经常加入管道符号来
#+BEGIN_SRC sh
$ps -aux | grep xfce
#+END_SRC

** TODO top

** kill
1. 可以杀死进程
   #+BEGIN_SRC sh
   $kill -9 id 
   #+END_SRC
   
2. 全部杀死进程
   #+BEGIN_SRC sh
   $killall idname
   #+END_SRC

** TODO fg | bg | & | jobs[1/4]
- [X] fg 后面加上进程的后台号码就能够将进程前台化
- [ ] bg 还不会用
- [ ] & 加在命令的后面可以将命令后台化
- [ ] jobs 还不会用


** Ctrl-Z | Ctrl-C
1. Ctrl-z 是将程序挂起
   挂起后还会显示一个进程号码
   用于fg 的时候前台化进程
2. Ctrl-c 是终止前台正在运行的程序


* 网络相关呢的信息

** 查看网卡硬件信息
#+BEGIN_SRC sh
$lshw -C network
#+END_SRC


** ifconfig
#+BEGIN_SRC sh
$apt-get install net-tools
$sudo ifconfig  # 现实当前激活的网络端口信息
#+END_SRC


*** 各项参数的解释
|--------------------------------+-------------------------------------------------------------------------|
| 缩写                           | 	含义                                                            |
|--------------------------------+-------------------------------------------------------------------------|
| lo                             | 回环接口                                                                |
| eth0 或 enp*                   | 以太网接口                                                              |
| wlan0                          | 	无线网接口                                                      |
| ppp0                           | 	点对点协议接口(拨号调制解调器PPTP,VPN,连接或,USB调制解调器使用) |
| vboxnet0 或 vmnet*             | 虚拟机网络接口                                                          |
| link encap                     | 网络类型，Ethernet是以太网                                              |
| HWaddr                         | 网卡MAC地址                                                             |
| Inet addr                      | IP地址                                                                  |
| Bcast                          | 广播地址                                                                |
| Mask                           | 子网掩码                                                                |
| UP BROADCAST RUNNING MULTICAST | 网卡运行状态                                                            |
| MTU                            | 最大传输单元                                                            |
| collisions                     | 以太网发生冲突的次数，如果该值过高，就要考虑网络硬件故障                |
| RX packets,TX packets          | 接收和发送的数据包数量；                                                |
| RX byte，TX byte               | 表示接搜和传输的具体数目                                                |
| Interrupt                      | 中断信息                                                                |
|--------------------------------+-------------------------------------------------------------------------|
** 查看所有的监听端口
#+BEGIN_SRC sh
netstat -lntp
#+END_SRC


** 查看所有已建立的链接
#+BEGIN_SRC sh
netstat -antp
#+END_SRC

* 用户相关
** 查看有多少个用户后
#+BEGIN_SRC sh
cat /etc/passwd #查看passwd文件
cut -d: -f1 /etc/passwd #查看所有用户名称
cut -d: -f1 /etc/passwd | wc -l #用wc计算出有多少个用户
#+END_SRC

** 查看有多少个族群
#+BEGIN_SRC sh
cat /etc/group #查看group文件
cut -d: -f1 /etc/group #查看所有用户名称
cut -d: -f1 /etc/group | wc -l #用wc计算出有多少个
#+END_SRC

** 查看用户登录日志
#+BEGIN_SRC sh
last
#+END_SRC
** 查看用户的基本信息
#+BEGIN_SRC sh
id <usename>
#+END_SRC

* inxi和lshw命令可以概述所有的信息
1. inxi 
   #+BEGIN_SRC sh
   inxi -Fxz
   #+END_SRC
   -F完整输出
   -x增加细节
   -z隐藏mac和ip等信息

2. lshw
   #+BEGIN_SRC sh
   lshw -short
   #+END_SRC


* 查看uefi和biso的信息

这条命令显示了 UEFI 或 BIOS 的日期和版本
#+BEGIN_SRC sh
dmidecode -t bios
#+END_SRC

* 总结1
#+BEGIN_SRC sh
  uname -a # 查看内核/操作系统/CPU信息
  head -n 1 /etc/issue # 查看操作系统版本
  cat /proc/cpuinfo # 查看CPU信息
  hostname # 查看计算机名
  lspci -tv # 列出所有PCI设备
  lsusb -tv # 列出所有USB设备
  lsmod # 列出加载的内核模块
  env # 查看环境变量资源
  free -m # 查看内存使用量和交换区使用量
  df -h # 查看各分区使用情况
  du -sh <目录名> # 查看指定目录的大小
  grep MemTotal /proc/meminfo # 查看内存总量
  grep MemFree /proc/meminfo # 查看空闲内存量
  uptime # 查看系统运行时间、用户数、负载
  cat /proc/loadavg # 查看系统负载磁盘和分区
  mount | column -t # 查看挂接的分区状态
  fdisk -l # 查看所有分区
  swapon -s # 查看所有交换分区
  hdparm -i /dev/hda # 查看磁盘参数(仅适用于IDE设备)
  dmesg | grep IDE # 查看启动时IDE设备检测状况网络
  ifconfig # 查看所有网络接口的属性
  iptables -L # 查看防火墙设置
  route -n # 查看路由表
  netstat -lntp # 查看所有监听端口
  netstat -antp # 查看所有已经建立的连接
  netstat -s # 查看网络统计信息进程
  ps -ef # 查看所有进程
  top # 实时显示进程状态用户
  w # 查看活动用户
  id <用户名> # 查看指定用户信息
  last # 查看用户登录日志
  cut -d: -f1 /etc/passwd # 查看系统所有用户
  cut -d: -f1 /etc/group # 查看系统所有组
  rontab -l # 查看当前用户的计划任务服务
#+END_SRC

* 总结2

#+BEGIN_SRC sh
inxi -Fxz 或 hwinfo --short 或 lshw  -short #显示所有硬件信息	
lscpu 或 lshw -C cpu  #CPU 信息
lshw -C cpu | grep -i capabilities #  显示 CPU 功能（例如 PAE、SSE2）	
lshw -C cpu | grep -i width  #报告 CPU 位数
dmidecode -t memory | grep -i size 或 lshw -short -C memory  #  显示当前内存大小和配置
dmidecode -t memory | grep -i max # 显示硬件支持的最大内存	
lshw -short -C memory | grep -i empty #（输出为空表示没有可用插确定是否有空闲内存插槽槽）
lspci | grep -i vga 然后指定设备号再次使用；    # 确定显卡内存数量	
例如：lspci -v -s 00:02.0 显卡内存数量就是 prefetchable 的值
free -m 或 top  #显示当前内存使用情况
lshw -short -C disk  #列出磁盘驱动器
hdparm -i /dev/sda（需要的话替换掉 sda）  #显示指定磁盘驱动器的详细信息
lsblk（简单） 或 fdisk -l（详细）  #列出磁盘和分区信息
blkid  #列出分区 ID（UUID）	  
df -m  # 列出已挂载文件系统挂载点以及已用和可用空间
lsusb # 列出 USB 设备
lspci # 列出 PCI 设备
lshw -C network # 显示网卡详细信息
ifconfig -a 或 ip link show 或 netstat -i # 显示网络接口
ip route | column -t 或 netstat -r # 显示路由表
dmidecode -t bios # 显示 UEFI/BIOS 信息
uname -a  #显示内核版本网络主机名等
#+END_SRC
